// SPDX-License-Identifier: MIT
// TetraFormer / TetraZero -- Cobra-backed legal placement generation.
//
// The placement set is generated by the vendored cobra-movegen backend.  The
// small compatibility layer below translates Cobra's fixed 10-column bitboard
// and piece-coordinate API into Tetra's ruleset, action, and timing types.
#pragma once

#include "tetra/legacy_movegen.hpp"

#include <cstdint>
#include <unordered_set>
#include <vector>

namespace tetra {
namespace cobra_movegen_detail {

std::uint64_t placement_key(const ActivePiece& piece);
bool collect_targets(const Board& board, Piece piece, const RulesetConfig& cfg,
                     std::unordered_set<std::uint64_t>& out);

}  // namespace cobra_movegen_detail

class MoveGenerator {
public:
    using Options = LegacyMoveGenerator::Options;

    MoveGenerator() = default;
    explicit MoveGenerator(const Options& options) : options_(options), legacy_(options) {}

    std::vector<PlacementAction> generate_for_piece(const Board& board, Piece piece,
                                                    const RulesetConfig& cfg,
                                                    bool use_hold) const {
        std::vector<PlacementAction> legacy_actions =
            legacy_.generate_for_piece(board, piece, cfg, use_hold);

        std::unordered_set<std::uint64_t> cobra_targets;
        if (!cobra_movegen_detail::collect_targets(board, piece, cfg, cobra_targets))
            return legacy_actions;

        // Cobra is authoritative for the legal placement set.  The legacy
        // layer supplies the project's canonical input and timing metadata,
        // which use a different SoftDrop convention than Cobra's pathfinder.
        std::vector<PlacementAction> out;
        out.reserve(legacy_actions.size());
        for (const PlacementAction& action : legacy_actions) {
            if (cobra_targets.contains(
                    cobra_movegen_detail::placement_key(action.piece_state())))
                out.push_back(action);
        }
        return out;
    }

    std::vector<PlacementAction> generate(const Board& board, Piece current, Piece hold_piece,
                                          Piece next_after_hold, const RulesetConfig& cfg) const {
        std::vector<PlacementAction> out = generate_for_piece(board, current, cfg, false);
        if (!options_.include_hold || !cfg.randomizer.hold_enabled) return out;

        const Piece swapped = (hold_piece != Piece::None) ? hold_piece : next_after_hold;
        if (swapped == Piece::None || swapped == current) return out;

        std::vector<PlacementAction> held = generate_for_piece(board, swapped, cfg, true);
        out.insert(out.end(), held.begin(), held.end());
        return out;
    }

    static std::vector<PlacementAction> expand_delay_bins(
        const std::vector<PlacementAction>& actions, const RulesetConfig& cfg, Tick now,
        Tick next_garbage_activation = TICK_NEVER, Tick opponent_next_lock = TICK_NEVER,
        const std::vector<DelayBin>& bins = default_delay_bins()) {
        return LegacyMoveGenerator::expand_delay_bins(
            actions, cfg, now, next_garbage_activation, opponent_next_lock, bins);
    }

    const Options& options() const { return options_; }

private:
    Options options_{};
    LegacyMoveGenerator legacy_{};
};

}  // namespace tetra
